name: Elastic beanstalk workflow

on:
  push:
    branches:
      - "master"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          application_name: ${{secrets.EB_APPLICATION_NAME}}
          environment_name: ${{secrets.EB_ENVIRONMENT_NAME}}
          version_label: 123456
          region: ${{secrets.AWS_REGION}}
          deployment_package: deploy.zip
          use_existing_version_if_available: true

